config/urls.py
from django.contrib import admin
from django.urls import path, include
#from core.index.views import IndexView
from core.login.views import *

from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('', LoginFormView.as_view(), name='login'),
    path('login/', include('core.login.urls')),
    path('admin/', admin.site.urls),
    path('home/', include('core.home.urls')),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

core/home/urls.py
from django.urls import path

from core.home.views.inicio.views import *

from core.home.views.servicios.views import *

from core.home.views.empleado.views import *

from core.home.views.facturas.views import *

from core.home.views.detalles.views import *

from core.home.views.ingresos.views import *

from core.home.views.productos.views import *

from core.home.views.proveedores.views import *

from core.home.views.egresos.views import *

from core.home.views.salidas_fijas.views import *

from core.home.views.detalles_servicio.views import *

from core.home.views.clientes.views import *

app_name = 'home'

urlpatterns = [
        #home
    path('inicio/', InicioView.as_view(), name='inicio'),
    
    #servicios
    path('sv/list', ServicioListView.as_view(), name='servicio_list'),
    path('sv/add/', ServicioCreateView.as_view(), name='servicio_create'),
    path('sv/update/<str:pk>/', ServicioUpdateView.as_view(), name='servicio_update'),
    path('sv/delete/<str:pk>/', ServicioDeleteView.as_view(), name='servicio_delete'),

    #empleados
    path('empleado/list', EmpleadoListView.as_view(), name='empleado_list'),
    path('empleado/add/', EmpleadoCreateView.as_view(), name='empleado_create'),
    path('empleado/update/<str:pk>/', EmpleadoUpdateView.as_view(), name='empleado_update'),
    path('empleado/delete/<str:pk>/', EmpleadoDeleteView.as_view(), name='empleado_delete'),

    #facturas
    path('facturas/list', FacturaListView.as_view(), name='factura_list'),
    path('facturas/add/', FacturasCreateView.as_view(), name='factura_create'),
    path('facturas/update/<str:pk>/', FacturaUpdateView.as_view(), name='factura_update'),
    path('facturas/delete/<str:pk>/', FacturaDeleteView.as_view(), name='factura_delete'),

#detalles_facturas
    path('detalles_facturas/list', Detalles_facturasListView.as_view(), name='detalles_facturas_list'),
    path('detalles_facturas/add/', Detalles_facturasCreateView.as_view(), name='detalles_facturas_create'),
    path('detalles_facturas/update/<str:pk>/',Detalles_facturasUpdateView.as_view(), name='detalles_facturas_update'),
    path('detalles_facturas/delete/<str:pk>/',Detalles_facturasDeleteView.as_view(), name='detalles_facturas_delete'),

    path('ingresos/list', IngresosListView.as_view(), name='ingresos_list'),
    path('ingresos/add/', IngresosCreateView.as_view(), name='ingresos_create'),
    path('ingresos/update/<str:pk>/',IngresosUpdateView.as_view(), name='ingresos_update'),
    path('ingresos/delete/<str:pk>/',IngresosDeleteView.as_view(), name='ingresos_delete'),

    path('productos/list', ProductosListView.as_view(), name='productos_list'),
    path('productos/add/', ProductosCreateView.as_view(), name='productos_create'),
    path('productos/update/<str:pk>/', ProductosUpdateView.as_view(), name='productos_update'),
    path('productos/delete/<str:pk>/', ProductosDeleteView.as_view(), name='productos_delete'),

    path('proveedores/list', ProveedoresListView.as_view(), name='proveedores_list'),
    path('proveedores/add/', ProveedoresCreateView.as_view(), name='proveedores_create'),
    path('proveedores/update/<str:pk>/', ProveedoresUpdateView.as_view(), name='proveedores_update'),
    path('proveedores/delete/<str:pk>/', ProveedoresDeleteView.as_view(), name='proveedores_delete'),

    path('egresos/list', EgresosListView.as_view(), name='egresos_list'),
    path('egresos/add/', EgresosCreateView.as_view(), name='egresos_create'),
    path('egresos/update/<str:pk>/', EgresosUpdateView.as_view(), name='egresos_update'),
    path('egresos/delete/<str:pk>/', EgresosDeleteView.as_view(), name='egresos_delete'),

    path('salidas_fijas/list', Salidas_fijasListView.as_view(), name='salidas_fijas_list'),
    path('salidas_fijas/add/', Salidas_fijasCreateView.as_view(), name='salidas_fijas_create'),
    path('salidas_fijas/update/<str:pk>/', Salidas_fijasUpdateView.as_view(), name='salidas_fijas_update'),
    path('salidas_fijas/delete/<str:pk>/', Salidas_fijasDeleteView.as_view(), name='salidas_fijas_delete'),

    path('detalles_servicio/list', Detalles_servicioListView.as_view(), name='detalles_servicio_list'),
    path('detalles_servicio/add/', Detalles_servicioCreateView.as_view(), name='detalles_servicio_create'),
    path('detalles_servicio/update/<str:pk>/', Detalles_servicioUpdateView.as_view(), name='detalles_servicio_update'),
    path('detalles_servicio/delete/<str:pk>/', Detalles_servicioDeleteView.as_view(), name='detalles_servicio_delete'),

    path('cliente/list', ClienteListView.as_view(), name='cliente_list'),
    path('cliente/add/', ClienteCreateView.as_view(), name='cliente_create'),
    path('cliente/update/<str:pk>/', ClienteUpdateView.as_view(), name='cliente_update'),
    path('cliente/delete/<str:pk>/', ClienteDeleteView.as_view(), name='cliente_delete'),
]

core/home/views/clientes/views.py
from django.contrib.auth.decorators import login_required
from django.http import JsonResponse
from django.urls import reverse_lazy
from django.utils.decorators import method_decorator
from django.views.decorators.csrf import csrf_exempt
from django.views.generic import ListView, CreateView, UpdateView, DeleteView

from core.home.forms import *
from core.home.models import Cliente


class ClienteListView(ListView):
    model = Cliente
    template_name = 'clientes/list.html'

    # permission_required = 'view_cartas'

    @method_decorator(csrf_exempt)
    def dispatch(self, request, *args, **kwargs):
        return super().dispatch(request, *args, **kwargs)

    def post(self, request, *args, **kwargs):
        data = {}
        try:
            action = request.POST['action']
            if action == 'searchdata':
                data = []
                for i in Cliente.objects.all():
                    data.append(i.toJSON())
            else:
                data['error'] = 'Ha ocurrido un error'
        except Exception as e:
            data['error'] = str(e)
        return JsonResponse(data, safe=False)

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['title'] = 'Listado de clientes'
        context['create_url'] = reverse_lazy('home:cliente_create')
        context['list_url'] = reverse_lazy('home:cliente_list')
        context['entity'] = 'Clientes'
        return context


class ClienteCreateView(CreateView):
    model = Cliente
    form_class = ClienteForm
    template_name = 'clientes/create.html'
    success_url = reverse_lazy('home:cliente_list')

    url_redirect = success_url

    def dispatch(self, request, *args, **kwargs):
        return super().dispatch(request, *args, **kwargs)

    def post(self, request, *args, **kwargs):
        data = {}
        try:
            action = request.POST['action']
            if action == 'add':
                form = self.get_form()
                data = form.save()
            else:
                data['error'] = 'No ha ingresado a ninguna opción'
        except Exception as e:
            data['error'] = str(e)
        return JsonResponse(data)

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['title'] = 'Creación de un cliente'
        context['entity'] = 'Cliente'
        context['list_url'] = self.success_url
        context['action'] = 'add'
        return context


class ClienteUpdateView(UpdateView):
    model = Cliente
    form_class = ClienteFormEdit
    template_name = 'clientes/create.html'
    success_url = reverse_lazy('home:cliente_list')

    url_redirect = success_url

    def dispatch(self, request, *args, **kwargs):
        self.object = self.get_object()
        return super().dispatch(request, *args, **kwargs)

    def post(self, request, *args, **kwargs):
        data = {}
        try:
            action = request.POST['action']
            if action == 'edit':
                form = self.get_form()
                data = form.save()
            else:
                data['error'] = 'No ha ingresado a ninguna opción'
        except Exception as e:
            data['error'] = str(e)
        return JsonResponse(data)

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['title'] = 'Edición de un Cliente'
        context['entity'] = 'Cliente'
        context['list_url'] = self.success_url
        context['action'] = 'edit'
        return context


class ClienteDeleteView(DeleteView):
    model = Cliente
    template_name = 'clientes/delete.html'
    success_url = reverse_lazy('home:cliente_list')

    url_redirect = success_url

    def dispatch(self, request, *args, **kwargs):
        self.object = self.get_object()
        return super().dispatch(request, *args, **kwargs)

    def post(self, request, *args, **kwargs):
        data = {}
        try:
            self.object.delete()
        except Exception as e:
            data['error'] = str(e)
        return JsonResponse(data)

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['title'] = 'Eliminación de un cliente'
        context['entity'] = 'Clientes'
        context['list_url'] = self.success_url
        return context

core/home/views/detalles/views.py
from django.contrib.auth.decorators import login_required
from django.http import JsonResponse
from django.urls import reverse_lazy
from django.utils.decorators import method_decorator
from django.views.decorators.csrf import csrf_exempt
from django.views.generic import ListView, CreateView, UpdateView, DeleteView

from core.home.forms import *
from core.home.models import detalles_facturas


class Detalles_facturasListView(ListView):
    model = detalles_facturas
    template_name = 'detalles/list.html'

    # permission_required = 'view_cartas'

    @method_decorator(csrf_exempt)
    def dispatch(self, request, *args, **kwargs):
        return super().dispatch(request, *args, **kwargs)

    def post(self, request, *args, **kwargs):
        data = {}
        try:
            action = request.POST['action']
            if action == 'searchdata':
                data = []
                for i in detalles_facturas.objects.all():
                    data.append(i.toJSON())
            else:
                data['error'] = 'Ha ocurrido un error'
        except Exception as e:
            data['error'] = str(e)
        return JsonResponse(data, safe=False)

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['title'] = 'Listado de detalles de facturas'
        context['create_url'] = reverse_lazy('home:detalles_facturas_create')
        context['list_url'] = reverse_lazy('home:detalles_facturas_list')
        context['entity'] = 'Detalles_facturas'
        return context


class Detalles_facturasCreateView(CreateView):
    model = detalles_facturas
    form_class = Detalles_facturasForm
    template_name = 'detalles/create.html'
    success_url = reverse_lazy('home:detalles_facturas_list')

    url_redirect = success_url

    def dispatch(self, request, *args, **kwargs):
        return super().dispatch(request, *args, **kwargs)

    def post(self, request, *args, **kwargs):
        data = {}
        try:
            action = request.POST['action']
            if action == 'add':
                form = self.get_form()
                data = form.save()
            else:
                data['error'] = 'No ha ingresado a ninguna opción'
        except Exception as e:
            data['error'] = str(e)
        return JsonResponse(data)

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['title'] = 'Creación de un Detalle de facturas'
        context['entity'] = 'Detalles_facturas'
        context['list_url'] = self.success_url
        context['action'] = 'add'
        return context


class Detalles_facturasUpdateView(UpdateView):
    model = detalles_facturas
    form_class = Detalles_facturasFormEdit
    template_name = 'detalles/create.html'
    success_url = reverse_lazy('home:detalles_facturas_list')

    url_redirect = success_url

    def dispatch(self, request, *args, **kwargs):
        self.object = self.get_object()
        return super().dispatch(request, *args, **kwargs)

    def post(self, request, *args, **kwargs):
        data = {}
        try:
            action = request.POST['action']
            if action == 'edit':
                form = self.get_form()
                data = form.save()
            else:
                data['error'] = 'No ha ingresado a ninguna opción'
        except Exception as e:
            data['error'] = str(e)
        return JsonResponse(data)

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['title'] = 'Edición de un Detalle de factura'
        context['entity'] = 'Detalle de factura'
        context['list_url'] = self.success_url
        context['action'] = 'edit'
        return context


class Detalles_facturasDeleteView(DeleteView):
    model = detalles_facturas
    template_name = 'detalles/delete.html'
    success_url = reverse_lazy('home:detalles_facturas_list')

    url_redirect = success_url

    def dispatch(self, request, *args, **kwargs):
        self.object = self.get_object()
        return super().dispatch(request, *args, **kwargs)

    def post(self, request, *args, **kwargs):
        data = {}
        try:
            self.object.delete()
        except Exception as e:
            data['error'] = str(e)
        return JsonResponse(data)

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['title'] = 'Eliminación de un detalle de factura'
        context['entity'] = 'Detalle_factura'
        context['list_url'] = self.success_url
        return context

core/home/views/inicio/views.py
from django.utils.decorators import method_decorator
from django.views.decorators.csrf import csrf_exempt

from django.views.generic import TemplateView


class InicioView(TemplateView):
    template_name = 'inicio.html'

    @method_decorator(csrf_exempt)
    def dispatch(self, request, *args, **kwargs):
        return super().dispatch(request, *args, **kwargs)

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['panel'] = 'Panel de administrador'

        return context

templates/delete.html
{% extends 'layout.html' %}

{% load widget_tweaks %}
{% block content %}
    <form method="post" action=".">
        <div class="card card-primary">
            <div class="card-header">
                <style>
                    .card-header{
                      background: #008374 !important;
                    }
               </style>
                
                <h3 class="card-title">
                    <i class="fas fa-trash"></i>
                    {{ title }}
                </h3>
            </div>
            <div class="card-body">
                {% csrf_token %}
                <input type="hidden" name="action" value="{{ action }}">
                {% if form.errors %}
                    <div class="alert alert-danger alert-dismissible">
                        <button type="button" class="close" data-dismiss="alert" aria-hidden="true">×</button>
                        <h5><i class="icon fas fa-ban"></i> Ha ocurrido un error al querer guardar el registro</h5>
                        <ul>
                            {% for field in form %}
                                {% for error in field.errors %}
                                    <li>{{ error }}</li>
                                {% endfor %}
                            {% endfor %}
                        </ul>
                    </div>
                {% endif %}
                <div class="alert alert-danger alert-dismissible">
                    <h5><i class="icon fas fa-ban"></i> Alerta!</h5>
                    ¿Estas seguro de eliminar el registro?
                </div>
            </div>
            <div class="card-footer">
                <button type="submit" class="btn btn-primary btn-flat">
                    <i class="fas fa-save"></i> Si, aceptar
                </button>
                <a href="{{ list_url }}" class="btn btn-danger btn-flat">
                    <i class="fas fa-times"></i> Cancelar
                </a>
            </div>
        </div>
    </form>
    <script>
        $('form').on('submit', function (e) {
            e.preventDefault();
            var parameters = new FormData(this);
            submit_with_ajax(window.location.pathname, 'Notificación', '¿Estas seguro de eliminar el siguiente registro?', parameters, function () {
                location.href = '{{ list_url }}';
            });
        });
    </script>
{% endblock %}

templates/footer.html
<!-- Main Footer -->

<footer id="footer" class="footer">

  <div class="container">
    <div class="row gy-4">
      <div class="col-lg-5 col-md-12 footer-info">
        <a href="#" class="logo d-flex align-items-center">
          <span>FamRub</span>
        </a>
        <div class="social-links d-flex mt-4">
          <a href="#" class="twitter"><i class="bi bi-twitter"></i></a>
          <a href="#" class="facebook"><i class="bi bi-facebook"></i></a>
          <a href="#" class="instagram"><i class="bi bi-instagram"></i></a>
          <a href="#" class="linkedin"><i class="bi bi-linkedin"></i></a>
        </div>
      </div>

      <div class="col-lg-2 col-6 footer-links">
        <h4>Useful Links</h4>
       
      </div>

      <div class="col-lg-2 col-6 footer-links">
        <h4>Our Services</h4>
       
      </div>

      <div class="col-lg-3 col-md-12 footer-contact text-center text-md-start">
        <h4>Contact Us</h4>
     

      </div>

    </div>
  </div>

  <div class="container mt-4">
    <div class="copyright">
      &copy; Copyright <strong><span>FamRub</span></strong>. All Rights Reserved
    </div>
    <div class="credits">
      <!-- All the links in the footer should remain intact. -->
      <!-- You can delete the links only if you purchased the pro version. -->
      <!-- Licensing information: https://bootstrapmade.com/license/ -->
      <!-- Purchase the pro version with working PHP/AJAX contact form: https://bootstrapmade.com/impact-bootstrap-business-website-template/ -->
      Designed by <a href="#">Sia</a>
    </div>
  </div>

</footer><!-- End Footer -->
<!-- End Footer --

templates/form.html
{% extends 'layout.html' %}
{% load widget_tweaks %}
{% block head %}
    {% block head_form %}

    {% endblock %}
{% endblock %}
{% block content %}
    <form method="post" action="." enctype="multipart/form-data">
        <div class="card card-primary">
            <div class="card-header">
                <style>
                    .card-header{
                      background: #008374 !important;
                    }
               </style>
                <h3 class="card-title">
                    {% if action == 'add' %}
                        <i class="fas fa-plus"></i>
                    {% else %}
                        <i class="fas fa-edit"></i>
                    {% endif %}

                    {{ title }}
                </h3>
            </div>
            <div class="card-body">
                {% csrf_token %}
                <input type="hidden" name="action" value="{{ action }}">
                {% if form.errors %}
                    <div class="alert alert-danger alert-dismissible">
                        <button type="button" class="close" data-dismiss="alert" aria-hidden="true">×</button>
                        <h5><i class="icon fas fa-ban"></i> Ha ocurrido un error al querer guardar el registro</h5>
                        <ul>
                            {% for field in form %}
                                {% for error in field.errors %}
                                    <li>{{ error }}</li>
                                {% endfor %}
                            {% endfor %}
                        </ul>
                    </div>
                {% endif %}
                {% for field in form.visible_fields %}
                    <div class="form-group">
                        <label for="email">{{ field.label }}:</label>
                        {{ field|add_class:'form-control'|attr:'autocomplete:off' }}
                    </div>
                {% endfor %}
            </div>
            <div class="card-footer">
                <button type="submit" class="btn btn-primary btn-flat">
                    <i class="fas fa-save"></i> Guardar registro
                </button>
                <a href="{{ list_url }}" class="btn btn-danger btn-flat">
                    <i class="fas fa-times"></i> Cancelar
                </a>
            </div>
        </div>
    </form>
    <script>
        {% if form.errors %}
            var errors = '';
            {% for field in form %}
                {% for error in field.errors %}
                    errors += '{{ error }}\n';
                {% endfor %}
            {% endfor %}
            {% for error in form.non_field_errors %}
                errors += '{{ error }}\n';
            {% endfor %}
            Swal.fire({
                title: 'Error!',
                text: errors,
                icon: 'error'
            });
        {% endif %}

        $('form').on('submit', function (e) {
            e.preventDefault();
            var parameters = new FormData(this);
            submit_with_ajax(window.location.pathname, 'Notificación', '¿Estas seguro de realizar la siguiente acción?', parameters, function () {
                location.href = '{{ list_url }}';
            });
        });
    </script>
{% endblock %}

templates/home.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta http-equiv="x-ua-compatible" content="ie=edge">
    <link href="{% static 'img/logo.png' %}" rel="icon">
    <!-- <title>{{ title }}</title> -->
    <title>Games Services</title>
    <!-- Font Awesome Icons -->
    <link rel="stylesheet" href="{% static 'lib/adminlte-3.0.4/plugins/font-awesome-5.11.1/css/all.min.css' %}">
    <!-- Theme style -->
    <link rel="stylesheet" href="{% static 'lib/adminlte-3.0.4/css/adminlte.min.css' %}">
    <!-- Google Font: Source Sans Pro -->
    <link href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,400i,700" rel="stylesheet">
    <!-- jQuery -->
    <script src="{% static 'lib/adminlte-3.0.4/plugins/jquery/jquery.min.js' %}"></script>
    <!-- Bootstrap 4 -->
    <script src="{% static 'lib/adminlte-3.0.4/plugins/bootstrap/js/bootstrap.bundle.min.js' %}"></script>
    <!-- AdminLTE App -->
    <script src="{% static 'lib/adminlte-3.0.4/js/adminlte.min.js' %}"></script>
    <!-- Sweetalert2 -->
    <script src="{% static 'lib/sweetalert2-9.10.0/sweetalert2.all.min.js' %}"></script>
    <!-- Jquery Confirm -->
    <link rel="stylesheet" href="{% static 'lib/jquery-confirm-v3.3.4/jquery-confirm.min.css' %}">
    <script src="{% static 'lib/jquery-confirm-v3.3.4/jquery-confirm.min.js' %}"></script>
    <!-- My css -->
    <link rel="stylesheet" href="{% static 'css/mystyle.css' %}">
    <!-- Functions -->
    <script src="{% static 'js/functions.js' %}"></script>
    <!-- Block head -->
<!-- nuevo-->
<link href="{% static 'st/vendor/bootstrap/css/bootstrap.min.css' %}" rel="stylesheet">
<link href="{% static 'st/vendor/bootstrap-icons/bootstrap-icons.css' %}" rel="stylesheet">
<link href="{% static 'st/vendor/aos/aos.css' %}" rel="stylesheet">
<link href="{% static 'st/vendor/glightbox/css/glightbox.min.css' %}" rel="stylesheet">
<link href="{% static 'st/vendor/swiper/swiper-bundle.min.css' %}" rel="stylesheet">

<!-- Template Main CSS File -->
<link href="{% static 'st/css/main.css' %}" rel="stylesheet">

<!-- nuevo-->
    {% block head %}

    {% endblock %}
    <script>
        // Función para obtener la fecha y hora actual en formato legible
        function getCurrentDateTime() {
            const now = new Date();
            const options = { weekday: 'long', year: 'numeric', month: 'long', day: 'numeric', hour: 'numeric', minute: 'numeric', second: 'numeric', timeZoneName: 'short' };
            return now.toLocaleDateString('es-ES', options);
        }

        // Función para actualizar la fecha y hora actual cada segundo
        function updateDateTime() {
            const dateTimeElement = document.getElementById('current-date-time');
            if (dateTimeElement) {
                dateTimeElement.textContent = getCurrentDateTime();
            }
        }

        // Actualizar la fecha y hora actual inicialmente
        updateDateTime();

        // Actualizar la fecha y hora cada segundo
        setInterval(updateDateTime, 1000);
    </script>
</head>
{% block body %}
<script src="{% static 'st/vendor/bootstrap/js/bootstrap.bundle.min.js' %}"></script>
<script src="{% static 'st/vendor/aos/aos.js' %}"></script>
<script src="{% static 'st/vendor/glightbox/js/glightbox.min.js' %}"></script>
<script src="{% static 'st/vendor/purecounter/purecounter_vanilla.js' %}"></script>
<script src="{% static 'st/vendor/swiper/swiper-bundle.min.js' %}"></script>
<script src="{% static 'st/vendor/isotope-layout/isotope.pkgd.min.js' %}"></script>
<script src="{% static 'st/vendor/php-email-form/validate.js' %}"></script>

<!-- Template Main JS File -->
<script src="{% static 'st/js/main.js' %}"></script>
{% endblock %}
</html>

templates/inicio.html
{% extends 'layout.html' %}
{% load static %}

{% block head %}

<script src="{% static 'lib/highcharts-8.1.2/highcharts.js' %}"></script>
<script src="{% static 'lib/highcharts-8.1.2/modules/exporting.js' %}"></script>
<script src="{% static 'lib/highcharts-8.1.2/modules/export-data.js' %}"></script>
<script src="{% static 'lib/highcharts-8.1.2/modules/accessibility.js' %}"></script>

{% endblock head %}


{% block content %}
<nav class="navbar p-0">
    <a class="navbar-brand mx-auto" href="#">
      <!---Logo-->
      <img src="{% static 'img/logo.png' %}" width="200" height="200" alt="logo de active games">
    </a>
  </nav>
  <!--titulos-->
  <div class="titulos">
    <h1>Ejemplo de titulo </h1>
    <p>Ejemplo descripción</p>
  </div>




{% endblock content %}

templates/layout.html
{% extends 'hzt/body.html' %}

templates/list.html
{% extends 'layout.html' %}
{% load static %}
{% block head %}
    <link rel="stylesheet" href="{% static 'lib/datatables-1.10.20/css/dataTables.bootstrap4.min.css' %}"/>
    <link rel="stylesheet"
          href="{% static 'lib/datatables-1.10.20/plugins/responsive-2.2.3/css/responsive.bootstrap4.min.css' %}"/>
    <script src="{% static 'lib/datatables-1.10.20/js/jquery.dataTables.js' %}"></script>
    <script src="{% static 'lib/datatables-1.10.20/js/dataTables.bootstrap4.min.js' %}"></script>
    <script src="{% static 'lib/datatables-1.10.20/plugins/responsive-2.2.3/js/dataTables.responsive.min.js' %}"></script>
    <script src="{% static 'lib/datatables-1.10.20/plugins/responsive-2.2.3/js/responsive.bootstrap4.min.js' %}"></script>

    {% block head_list %}
   

    {% endblock %}

{% endblock %}

{% block content %}
    <div class="card card-primary">

        <div class="card-header">
            <style>
                .card-header{
                  background: #008374 !important;
                }
           </style>
        
            <h3 class="card-title">
                <img src="{% static 'img/logo.png' %}" class="icon" alt="Logo" style="width: 24px; height: 24px; margin-right: 8px;">
                {{ title }}
            </h3>
        </div>
        <div class="card-body">
            
            <table class="table table-bordered" id="data">
               
                <thead>
                {% block columns %}

                {% endblock %}
                </thead>
                <tbody>
                {% block rows %}

                {% endblock %}
                </tbody>
            </table>
        </div>
        <div class="card-footer">
           
            {% block buttons_list %}
                <a href="{{ create_url }}" class="btn btn-primary btn-flat btnTest" >
                    <i class="fas fa-plus"></i> Agregar
                </a>
                <a href="{{ list_url }}" class="btn btn-success btn-flat">
                    <i class="fas fa-sync"></i> Actualizar
                </a>
            {% endblock %}
        </div>
    </div>
{% endblock %}

{% block javascript %}
    <script type="application/javascript">
        $(function () {
            $('#data').DataTable({
                responsive: true,
                autoWidth: false
            });

            $('.btnTest').on('click', function () {
                $.ajax({
                    url: '{% url 'home:empleado_list' %}',
                    type: 'POST',
                    data: {id: 1},
                    dataType: 'json'
                }).done(function (data) {
                    console.log(data);
                }).fail(function (jqXHR, textStatus, errorThrown) {
                    alert(textStatus + ': ' + errorThrown);
                }).always(function (data) {

                });
            });
        });
    </script>
{% endblock %}